name: Job Watch (Uber + Microsoft)

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes (UTC)
  workflow_dispatch: {} # manual runs

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      # Scheduled run – normal monitoring (time window + de-dupe)
      - name: Watch (scheduled)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          python watch_all.py

      # Manual run – test + one-time full dump for BOTH in ONE email
      - name: Watch (manual test + dump)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: |
          python watch_all.py --test-email
          python watch_all.py --ignore-window --send-all-now --msft-pages=5
