name: Job Watch (Uber)

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing back to the repo
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run job watcher
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python watch_uber.py

      - name: Commit updated seen file
        run: |
          if [ -f seen_uber.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add seen_uber.json
            git commit -m "Update seen_uber.json [skip ci]" || echo "No changes to commit"
            git push
          fi
