name: Uber Watch

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes, UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run watcher
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }} # optional, defaults to Gmail
          SMTP_PORT: ${{ secrets.SMTP_PORT }} # optional, defaults to 465
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python watch_uber.py
